CONNECT system/"Bhargav@9182"@localhost:1521/XEPDB1
CREATE USER vehiclerental IDENTIFIED BY vehiclerental123;
GRANT CONNECT, RESOURCE, CREATE SESSION TO vehiclerental;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO vehiclerental;
ALTER USER vehiclerental QUOTA UNLIMITED ON USERS;
EXIT;
